### ISSUE TITLE
Add static PV Support

### ISSUE THREAD

**Issue by jlpedrosa** [M0NsTeRRR/helm-charts#44]
**What would you like to be added**:
Self ticket to enable static PV links to the PVC via volume name.

**Why is this needed**:
To be able to reuse volumes across k8s reinstalls (among other things).

**Comment by M0NsTeRRR** [comment]
Is this issue can be closed ? (regarding https://github.com/M0NsTeRRR/helm-charts/pull/45)

**Comment by jlpedrosa** [comment]
I think so, I didn't find any other pv

**Comment by jlpedrosa** [comment]
Thanks for your projects!

**Comment by M0NsTeRRR** [comment]
Thanks for you contribution :)
