### ISSUE TITLE
Trouble with torrent port using the qbittorrent helm chart

### ISSUE THREAD

**Issue by ghost** [M0NsTeRRR/helm-charts#93]
Hello,
Im trying to deploy your qbittorrent helm chart but im experiencing some issues with the torrent. 

While troubleshooting i found some things in the templates that i dont fully understand so this issue is to get a bit of an explanation of the deployment template:

1) in torrenservice.yaml are the ports defined by: "{{ .Values.service.torrent.port }}" which i understand
    but in deployment.yaml at line 49 are torrent-tcp and torrent-udp hardcoded to 6881 shoudlnt this also be "{{ .Values.service.torrent.port }}" ?

2) At line 61 of deployment.yaml the .env QBITTORRENT__BT_PORT gets defined to "8388". This is where it confuses me. Shouldnt it be set to the same port as torrent-udp and torrent-tcp?

3) At line 93 of deployment.yaml shows the port 8388 itself again as shadowsocks-tcp and shadowsocks-udp. What does this mean?

If you could help me out that would be awesome, thanks in advance!

**Comment by M0NsTeRRR** [comment]
Hello :)

> 1. in torrenservice.yaml are the ports defined by: "{{ .Values.service.torrent.port }}" which i understand
but in deployment.yaml at line 49 are torrent-tcp and torrent-udp hardcoded to 6881 shoudlnt this also be "{{ .Values.service.torrent.port }}" ?

In `torrentservice.yaml`, port refers to the service port and targetPort to the pod port. In this case, the ports named `torrent-tcp` and `torrent-udp` defined in `deployment.yaml`.

> 2. At line 61 of deployment.yaml the .env QBITTORRENT__BT_PORT gets defined to "8388". This is where it confuses me. Shouldnt it be set to the same port as torrent-udp and torrent-tcp?

Yes, good catch! I've fixed the issue in the latest version and removed the environment variable to use the default container port.


> 3. At line 93 of deployment.yaml shows the port 8388 itself again as shadowsocks-tcp and shadowsocks-udp. What does this mean?

It corresponds to Gluetun ports, not the qBittorrent one. I defined them, but I don't use them in the rest of the chart. However, we could create a service for that.
https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/

**Comment by M0NsTeRRR** [comment]
Thanks you, you too.
If you need some examples of configuration for these charts, you can take a look here: https://github.com/M0NsTeRRR/homelabv3-infra/tree/main/argocd

**Comment by M0NsTeRRR** [comment]
@reinoudb `FIREWALL_INPUT_PORTS` should only need port `80`

**Comment by M0NsTeRRR** [comment]
Yes it could be an enhancement for sure, but from a security perspective I prefer to keep everything blocked and let the user open what he needs
